### ISSUE TITLE
Support submitting multiple requests in sample CLI

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#100]
Beyond just simple demonstration, we might want to allow creating some workload. We can extend the sample `peer request` command to support submitting a series of requests back-to-back. Then this could be used to imitate some dense workload.

**Comment by nhoriguchi** [comment]
If we allow `peer request` to send multiple requests, we need to design how we pass the separate input strings from command line. The simplest way is using multiple string arguments like below
~~~
$ peer request "First request" "Second request" "Third request"
~~~
which sends 3 requests. But considering the limit on bash command input (controlled by `getconf ARG_MAX`), we may have a way of file-based input to generate multiple requests.
~~~
$ cat <INPUT_FILE>
First request
Second request
Third request
$ peer request -f <INPUT_FILE>
~~~

And when we discuss about the CLI interface, I also feel like discussing the way to specify CLIENT_ID. Currently we call `peer run` command with replica IDs, so I thought of doing similarly for `peer request` like below:
~~~
$ peer request <CLIENT_ID> "First request" "Second request" "Third request"
~~~
I'll try to write patches in this direction, and if you have any advice, feel free to let me know.

**Comment by nhoriguchi** [comment]
> And when we discuss about the CLI interface, I also feel like discussing the way to specify CLIENT_ID. Currently we call `peer run` command with replica IDs, so I thought of doing similarly for `peer request` like below:
> 
> ```
> $ peer request <CLIENT_ID> "First request" "Second request" "Third request"
> ```

ah, option "--id id" is already supported, so we just have to document it somewhere.

**Comment by sergefdrv** [comment]
We can also pass requests to `peer request` through standard input. 

Another possibility would be to add an option with a number of requests to generate. In that case, the argument might be treated as a `printf`-style format string.
