### ISSUE TITLE
Decapitalize error strings

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#105]
Note: It is said that error strings should not be capitalized, but our project use the capitalized style consistently.
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

_Originally posted by @ynamiki in https://github.com/hyperledger-labs/minbft/pull/102_

**Comment by nhoriguchi** [comment]
Sorry for mishandling of "assignee". @Romeo5929 is working on this issue now, although I can't find his account in "Assignees" list.

**Comment by ynamiki** [comment]
I think we can "assign" an issue to only a member of the [hyperledger-labs organization](https://github.com/orgs/hyperledger-labs/people)....

**Comment by nhoriguchi** [comment]
@ynamiki  thank you for clarifying, so let's keep "Assignee" blank, and just stating in comment that "he is working".

**Comment by ynamiki** [comment]
> @Romeo5929 is working on this issue now

Let's move this to the "In progress" column in the dashboard.

**Comment by sergefdrv** [comment]
> @Romeo5929 is working on this issue now

Please have a look at #106 as well, it might make sense to handle both at onc :wink:
