### ISSUE TITLE
Simplify messageString() output for large message payload

### ISSUE THREAD

**Issue by nhoriguchi** [hyperledger-labs/minbft#111]
I noticed in "MinBFT on Fabric" trial that orderer's log output was filled with message payload, which was a bit cumbersome to handle. Showing raw payload might be good for some simple workload, but some digest might more preferable for messages with large payload. One possible way to go is to introduce a threshold and to show a digest value if the size of message payload goes above it.

**Comment by sergefdrv** [comment]
> One possible way to go is to introduce a threshold and to show a digest value if the size of message payload goes above it.

Another option is to abbreviate long values with ellipsis.

**Comment by nhoriguchi** [comment]
> > One possible way to go is to introduce a threshold and to show a digest value if the size of message payload goes above it.
> 
> Another option is to abbreviate long values with ellipsis.

Thanks, I'll do it.
