### ISSUE TITLE
Forward request messages to primary replica

### ISSUE THREAD

**Issue by nhoriguchi** [hyperledger-labs/minbft#119]
The sample client currently sends `REQUEST` messages to all replicas, but generally that's not a requirement.  The `REQUEST` messages are embedded in the corresponding `PREPARE` messages and distributed to backup replicas in prepare phase, so by allowing the backup replicas to forward the `REQUEST` messages to the primary replica at the time, clients can initiate requests just by sending at least one `REQUEST` message to one of the replicas.  This issue also covers changing the sample client to flexibly choose the target replicas of requesting for demonstration purpose.

**Comment by sergefdrv** [comment]
This looks like a good direction for optimization. The proposed change would indeed safely reduce communication overhead in graceful execution. However, any optimization needs to consider both safety and liveness. In order to preserve liveness in the worst case, at least `f+1` _correct_ replicas need to eventually receive the `REQUEST` message so that they can trigger view change. I think this proposal needs some extension/refinement to cover this.

**Comment by nhoriguchi** [comment]
> at least f+1 correct replicas need to eventually receive the REQUEST message so that they can trigger view change, ...

OK, it seems I've submitted this issue based on incorrect understanding on current code, sorry about that. Clients don't know which replica is primary or which replicas are correct/faulty, so all replicas should receive the REQUEST message to properly set request timers for now. If we have a reliable way to find a primary replica or faulty replicas, we might reduce the number of targets to send REQUEST messages.

I think that getting info about faulty replicas is important also for accountability, but it's not originally intended in this issue. So I'll create another issue when needed.

Thanks for the comment.

**Comment by sergefdrv** [comment]
I think there is a possibility to optimize the protocol in this direction. First, we can try some optimistic scheme. If that does not work, we can fall back to the original pessimistic, but reliable, scheme. However, we should not probably focus on optimization at this stage.

**Comment by nhoriguchi** [comment]
@sergefdrv I agree, so I close this issue now.
