### ISSUE TITLE
facing below error . kindly tell how to troubleshoot it?

### ISSUE THREAD

**Issue by adityaverma998** [hyperledger-labs/minbft#125]
shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft$ make install
make -C usig/sgx build
make[1]: Entering directory '/home/shalikram/minbft/usig/sgx'
make[1]: Nothing to be done for 'build'.
make[1]: Leaving directory '/home/shalikram/minbft/usig/sgx'
go build -o sample/build/keytool ./sample/authentication/keytool
sample/authentication/keytool/main.go:19:8: cannot find package "github.com/hyperledger-labs/minbft/sample/authentication/keytool/cmd" in any of:
	/usr/lib/go-1.10/src/github.com/hyperledger-labs/minbft/sample/authentication/keytool/cmd (from $GOROOT)
	/home/shalikram/go/src/github.com/hyperledger-labs/minbft/sample/authentication/keytool/cmd (from $GOPATH)
Makefile:55: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by sergefdrv** [comment]
@adityaverma998 Thanks for trying it out. Most likely, the problem is the version of Go. MinBFT relies on [Go modules](https://github.com/golang/go/wiki/Modules) that require at least Go v1.11. It looks like you are using Go v1.10, thus the error.

You may still try building MinBFT with Go v1.10, but then you need to move the code in `$GOPATH/src/github.com/hyperledger-labs/minbft`, which would be `/home/shalikram/go/src/github.com/hyperledger-labs/minbft` in your case.

**Comment by adityaverma998** [comment]
Thanks for your reply, i am using go latest version, that is, 1.13.4.
Kindly let me know how i can remove the error so that i can install it properly on my system.
Warm Regards.

**Comment by sergefdrv** [comment]
Could you please share the output of `go env` and `go version` on your build machine? From the output you already given, it seems like your `GOROOT` is `/usr/lib/go-1.10`...

**Comment by adityaverma998** [comment]
Thank you, sir, for the reply. After typing go version command on terminal I got, go 1.10.4, whereas I downloaded go1.13.4 from the official website, I don't know how it is go 1.10.4 . Kindly let me know how to update it?

**Comment by sergefdrv** [comment]
I guess you use some Ubuntu distribution. I suggest you try checking if you have Go installed as an OS package: `dpkg --status golang` and uninstall it with `apt-get remove golang`, in case it is installed. You can also use `which go` to check which binary gets executed by `go` command. Finally, `whereis go` should give some idea of where your system can locate `go`. Please ask if you need more help!

**Comment by adityaverma998** [comment]
Thank you for the reply, sir.
The version of my go was go1.10.4, which i now updated to go1.13.4.

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~$ go version
go version go1.13.4 linux/amd64

But, now i am facing a new error, kindly comment on this asap,

ERROR:

make -C usig/sgx build
make[1]: Entering directory '/home/shalikram/minbft/usig/sgx'
make[1]: Nothing to be done for 'build'.
make[1]: Leaving directory '/home/shalikram/minbft/usig/sgx'
go build -o sample/build/keytool ./sample/authentication/keytool
go: github.com/BurntSushi/toml@v0.3.1: Get https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod: proxyconnect tcp: dial tcp: lookup http: no such host
Makefile:55: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by sergefdrv** [comment]
It looks like a network problem. Could you try `go get github.com/golang/example/hello`?

**Comment by adityaverma998** [comment]
output of 
go get github.com/golang/example/hello?

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft$ go get github.com/golang/example/hello
go: github.com/BurntSushi/toml@v0.3.1: Get https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod: proxyconnect tcp: dial tcp: lookup http: no such host

**Comment by adityaverma998** [comment]
Thank you so much sir for all your help.
It was due to the proxy setup which we use in our institute IIIT ALLAHABAD. 
In case of any other query i will contact you.
Thank you for your kind help.

**Comment by sergefdrv** [comment]
Good luck!
