### ISSUE TITLE
Failed to generate keys: failed to create USIG enclave:

### ISSUE THREAD

**Issue by shalikpatel** [hyperledger-labs/minbft#126]
After running make install 
I am getting following error while executing command
bin/keytool generate -u lib/libusig.signed.so

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft$ cd sample
shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft/sample$ bin/keytool generate -u lib/libusig.signed.so
Using output file: keys.yaml
Error: Failed to generate keys: failed to create USIG enclave: libsgx_urts.so: cannot open shared object file: No such file or directory
Usage:
  keytool generate [numberReplicas [numberClients [usigEnclaveFile]]] [flags]

Flags:
      --client-key-spec string     keyspec for client (default "ECDSA")
      --client-sec-param int       client security param (default 256)
  -h, --help                       help for generate
  -c, --num-clients int            number of clients (default 1)
  -r, --num-replicas int           number of replicas (default 3)
      --replica-key-spec string    keyspec for replica (default "ECDSA")
      --replica-sec-param int      replica security param (default 256)
  -u, --usig-enclave-file string   USIG enclave file (default "libusig.signed.so")

Global Flags:
      --config string   config file (default "keytool.yaml")
  -o, --output string   output file (default "keys.yaml")

Failed to generate keys: failed to create USIG enclave: libsgx_urts.so: cannot open shared object file: No such file or directory

**Comment by nhoriguchi** [comment]
Hi @shalikpatel, could you make sure that environment variable `LD_LIBRARY_PATH` includes the directory path in which `libsgx_urts.so` is located (`/minbft/sample/lib` in your case)?

**Comment by shalikpatel** [comment]
Yes, I have done that using following command still I am getting same error, I have executed following commands

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft$ export LD_LIBRARY_PATH="${PWD}/sample/lib:$/minbft/sample/lib"

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft$ cd sample

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft/sample$ bin/keytool generate -u lib/libusig.signed.so
Using output file: keys.yaml
Error: Failed to generate keys: failed to create USIG enclave: libsgx_urts.so: cannot open shared object file: No such file or directory
Usage:
  keytool generate [numberReplicas [numberClients [usigEnclaveFile]]] [flags]

Flags:
      --client-key-spec string     keyspec for client (default "ECDSA")
      --client-sec-param int       client security param (default 256)
  -h, --help                       help for generate
  -c, --num-clients int            number of clients (default 1)
  -r, --num-replicas int           number of replicas (default 3)
      --replica-key-spec string    keyspec for replica (default "ECDSA")
      --replica-sec-param int      replica security param (default 256)
  -u, --usig-enclave-file string   USIG enclave file (default "libusig.signed.so")

Global Flags:
      --config string   config file (default "keytool.yaml")
  -o, --output string   output file (default "keys.yaml")

Failed to generate keys: failed to create USIG enclave: libsgx_urts.so: cannot open shared object file: No such file or directory

**Comment by nhoriguchi** [comment]
> Failed to generate keys: failed to create USIG enclave: libsgx_urts.so: cannot open shared object file: No such file or directory

I don't pinpoint the root cause yet, but it might be related to the discussion in #93. And I guess that you are trying to run Intel SGX in hardware mode (`SGX_MODE=HW`), so please note in case that your hardware supports SGX feature. You can check that with command `cat /proc/cpuinfo  | grep ' sgx '`.

**Comment by sergefdrv** [comment]
Have you tried

```sh
export LD_LIBRARY_PATH="${PWD}/sample/lib:${LD_LIBRARY_PATH}"
```

instead of 

```sh
export LD_LIBRARY_PATH="${PWD}/sample/lib:$/minbft/sample/lib"
```

SGX SDK's `environment` script extends `LD_LIBRARY_PATH`.

**Comment by shalikpatel** [comment]
Yes but same error

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft$ export LD_LIBRARY_PATH="${PWD}/sample/lib:${LD_LIBRARY_PATH}"

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft$ cd sample

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft/sample$ bin/keytool generate -u lib/libusig.signed.so
Using output file: keys.yaml
Error: Failed to generate keys: failed to create USIG enclave: libsgx_urts.so: cannot open shared object file: No such file or directory
Usage:
  keytool generate [numberReplicas [numberClients [usigEnclaveFile]]] [flags]

Flags:
      --client-key-spec string     keyspec for client (default "ECDSA")
      --client-sec-param int       client security param (default 256)
  -h, --help                       help for generate
  -c, --num-clients int            number of clients (default 1)
  -r, --num-replicas int           number of replicas (default 3)
      --replica-key-spec string    keyspec for replica (default "ECDSA")
      --replica-sec-param int      replica security param (default 256)
  -u, --usig-enclave-file string   USIG enclave file (default "libusig.signed.so")

Global Flags:
      --config string   config file (default "keytool.yaml")
  -o, --output string   output file (default "keys.yaml")

Failed to generate keys: failed to create USIG enclave: libsgx_urts.so: cannot open shared object file: No such file or directory


How to change hardware mode to simulation mode(If I am using hardware mode)

cat /proc/cpuinfo | grep ' sgx '.  cmd not doing anything
shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft/sample$ cat /proc/cpuinfo | grep ' sgx '
shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~/minbft/sample$

**Comment by sergefdrv** [comment]
It looks like you are trying to build hardware-based SGX USIG. Is that what you wanted? 

If so, could you please first check if your build machine has SGX support *enabled*, as suggested in https://github.com/hyperledger-labs/minbft/issues/126#issuecomment-555366539. If it has, please also make sure you have installed SGX driver and PSW *before* installing SGX SDK.

**Comment by sergefdrv** [comment]
@shalikpatel I was wondering if you need more help or we can close this issue?

**Comment by sergefdrv** [comment]
Closing because of no reply.
