### ISSUE TITLE
Try GitHub Actions

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#128]
GitHub Actions is now available. Even we don't have a strong motivation to move from our current CI (CircleCI), I would like to check the features and try the new service.

https://help.github.com/en/actions

**Comment by nhoriguchi** [comment]
We sometimes suffered from CircleCI issues, so I'm OK to migrate to GitHub Actions if it's really useful. My preference is that we individually tries the service for a few weeks/months, then discuss whether we like it or not.

**Comment by sergefdrv** [comment]
I agree with Naoya. Let's give it a try. Maybe we can have both enabled for the mean time?

**Comment by nhoriguchi** [comment]
FYI, comparison between these two CI systems is discussed [here](https://knapsackpro.com/ci_comparisons/circle-ci/vs/github-actions). Currently we only run unit tests, which requires no advanced features, so both systems seem to meet our demands.
