### ISSUE TITLE
Race condition for request execution

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#130]
Message streams from different replicas are processed concurrently. Even though PREPARE/COMMIT messages from the same replica are always processed sequentially, there is still a possible race condition for request execution. 

The race can happen because there is no synchronization in `makeCommitmentCollector` between invocations of `countCommitment` and `executeRequest`. It can happen that `countCommitment` returns `true` for two subsequent prepared requests in two goroutines. That is because one goroutine may first supply the last required commitment for one prepared request, whereas another goroutine can supply a commitment for the same prepared request (which is ignored) followed by the last required commitment of the subsequent prepared request. Then two goroutines will race to execute those requests.

**Comment by sergefdrv** [comment]
A possible solution could be to return a release function from `commitmentCounter`.

**Comment by sergefdrv** [comment]
Maybe a better way to fix this would be to protect the body of `commitmentCollector` returned from `makeCommitmentCollector` with a mutex.

**Comment by nhoriguchi** [comment]
I might miss something, but `retireSeq` checks and updates `lastRetiredSeq` atomically (within a single lock), so only one goroutine seems to call `executeRequest`. Is it important which goroutine executes the request?

**Comment by sergefdrv** [comment]
So the problem is that two goroutines can race to execute two different requests.
