### ISSUE TITLE
Mandatory parameters for timeout values

### ISSUE THREAD

**Issue by nhoriguchi** [hyperledger-labs/minbft#139]
We might be better to give parameters for clientstate or its timers as mandatory ones [as pointed out](https://github.com/hyperledger-labs/minbft/pull/127#discussion_r350675670) in #127.

I thought of passing `api.Configer` to `clientstate.NewProvider` in `defaultIncomingMessageHandler` but unit tests like `request-timeout_test.go` is affected by this change (that seems complicated to me). So I'm not sure that it's a good direction or worth doing at this point.

**Comment by sergefdrv** [comment]
I think we just need to pass the timeout duration to `clientstate.NewProvider`.

**Comment by nhoriguchi** [comment]
That's a simple way. I thought too serious to find an elegant way.
