### ISSUE TITLE
Contributing: Git hook to fix commit order in GitHub

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#141]
It is a [known issue](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-in-the-wrong-order) that GitHub shows commits according to commit author date rather than topologically. This creates confusion when commits are reordered with rebase/cherry-pick.

I found a [simple script](https://gist.github.com/sergefdrv/773eb052a64f8545ee2433c9e625606e) that updates author and commiter dates of the commit. This script can be used as a [git hook](https://git-scm.com/docs/githooks) to automatically reset the commit dates whenever a commit gets updated. I wonder if we should mention this in our contribution guideline?

**Comment by nhoriguchi** [comment]
> It is a [known issue](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-in-the-wrong-order) that GitHub shows commits according to commit author date rather than topologically. This creates confusion when commits are reordered with rebase/cherry-pick.

As long as I checked, GitHub WebUI shows commits in committer date order (not in author date order). And committer dates are updated to now with git-rebase and git-cherry-pick (even without the post-commit hook.) So I'm not sure how often the confusing situation happens.

**Comment by ynamiki** [comment]
I tried rebasing and it looks ordered as intended without the hook script....
https://github.com/ynamiki/commit-reordering/pull/1

**Comment by sergefdrv** [comment]
Apparently, GitHub ignores commit's author time, but not date. Please check https://github.com/sergefdrv/commit-reordering/pull/1 

![image](https://user-images.githubusercontent.com/11386423/70896174-8576f800-1ff0-11ea-88d1-ea155f908f31.png)

and compare with `git log --pretty=fuller`:

```
commit 7d6596f941459391821e323ad83f81bf39e93591 (HEAD -> pr)
Author:     Yuta Namiki <yuta.namiki@gmail.com>
AuthorDate: Mon Dec 16 07:44:05 2019 +0900
Commit:     Sergey Fedorov <sergey.fedorov@neclab.eu>
CommitDate: Mon Dec 16 10:39:06 2019 +0100

    Second commit: add file 2

commit 3f2323821405de920b240924f67ea9acadf15466
Author:     Sergey Fedorov <sergey.fedorov@neclab.eu>
AuthorDate: Mon Dec 16 10:29:13 2019 +0100
Commit:     Sergey Fedorov <sergey.fedorov@neclab.eu>
CommitDate: Mon Dec 16 10:39:06 2019 +0100

    Fourth commit: add file 4

commit 2c604c3a763d98c2e0c4f5e74d5c150e6b9ad9e2
Author:     Yuta Namiki <yuta.namiki@gmail.com>
AuthorDate: Mon Dec 16 07:44:26 2019 +0900
Commit:     Sergey Fedorov <sergey.fedorov@neclab.eu>
CommitDate: Mon Dec 16 10:39:06 2019 +0100

    Third commit: add file 3

```

**Comment by nhoriguchi** [comment]
This wrong ordering happens in pull request page, and [branch page](https://github.com/sergefdrv/commit-reordering/commits/pr) seems to show topological order, so you can rely on that page. But I don't object to introduce the hook script and I'm glad to install it on my environment.

**Comment by ynamiki** [comment]
> I'm glad to install it on my environment.

I do, too.

**Comment by sergefdrv** [comment]
Thank you for your feedback, I think we should mention this in the [contribution guideline](https://github.com/hyperledger-labs/minbft/blob/master/CONTRIBUTING.md).

**Comment by sergefdrv** [comment]
It turns out that post-commit hook is not a reliable trigger for this purpose. For instance, this hook is not invoked in non-interactive rebase: https://stackoverflow.com/a/58842291/3778878.

**Comment by sergefdrv** [comment]
As was [announced by GitHub](https://github.blog/changelog/2020-07-14-pull-request-commits-now-ordered-chronologically/), pull request commits are ordered according to their chronological order, which is consistent with the ordering in Git. Therefore, there is no need in any special care like a Git hook anymore :tada:
