### ISSUE TITLE
Environment checker in build process

### ISSUE THREAD

**Issue by nhoriguchi** [hyperledger-labs/minbft#150]
We have non-trivial prerequisite steps before running [Running Example](https://github.com/hyperledger-labs/minbft#running-example), which can be a barrier for early users. So some environment check and guidance messages might be helpful. For example, if we try to build on non-SGX system with SGX_MODE=HW, the warning like below should be helpful:
~~~
$ make install
Platform doesn't support Intel SGX. Please retry with environment variable SGX_MODE=SIM.
~~~

Similarly, if we try to build without meeting requirement, the error like below works well.
~~~
$ make install
Intel SGX SDK is not available on current platform, see README for requirements.
~~~

**Comment by nhoriguchi** [comment]
SGX hardware support checker is available [here](https://github.com/ayeks/SGX-hardware). It's a simple C program executing CPUID instruction to retrieve SGX capability, so the check should be reliable enough. So I'm now thinking of using this in this project.

I'm a little unsure about how. Maybe committing the source file with LICENSE file is a common way, but that could be another source of complexity around building. So if you are OK, it could be better to commit prebuilt binary file. The size of the binary is ~12kB, so maybe that's not a problem.

**Comment by sergefdrv** [comment]
Have you considered approaches described in [this article](https://software.intel.com/en-us/articles/properly-detecting-intel-software-guard-extensions-in-your-applications) from Intel?

**Comment by sergefdrv** [comment]
This notice looks alerting:

> **Applications that make decisions based solely on CPUID enumeration run the risk of generating a #GP or #UD fault at runtime.**

**Comment by nhoriguchi** [comment]
> Have you considered approaches described in [this article](https://software.intel.com/en-us/articles/properly-detecting-intel-software-guard-extensions-in-your-applications) from Intel?

Ah, I didn't check that. Thanks for the pointer 👍
