### ISSUE TITLE
CircleCI: Create and Use Custom Docker Image

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#16]
CircleCI, which we have set up in #13 supports custom Docker images so it is better to build a custom image with Intel SGX SDK and Go on Ubuntu 16.04 than to do everything in `.circleci/config.yml`.

A problem on using a custom image is that we need to have a Docker Registry or to manage an account of Docker Hub.

**Comment by ynamiki** [comment]
To do:
- [Doing in the chat] Ask an administrator to install "Docker Hub Registry" application in hyperledger-labs organization of GitHub
- [Waiting the first item] Update configuration of Docker Hub to refer hyperledger-labs/minbft for automated build (ynamiki/minbft is used now)

**Comment by ynamiki** [comment]
The above to-do items has been done. I have configured an autometed build from this repository.

**Comment by ynamiki** [comment]
CircleCI was failed because it could not get the image. I will take a look.

https://circleci.com/gh/hyperledger-labs/minbft/tree/master

**Comment by ynamiki** [comment]
The CI is now fixed (no changes, I just re-run the job); it seems that we need some time to get the latest image from Docker Hub.

**Comment by nhoriguchi** [comment]
@ynamiki (just off-topic comment...) sorry for letting you close this issue manually. I added the reference "solved #16" in merge commit message, but according to https://help.github.com/articles/closing-issues-using-keywords/, the word "solved" is not a magic word. I'll use right word if I'll do merge operation next.

**Comment by ynamiki** [comment]
@Naoya-Horiguchi No problem. It was my task to add the magic word in my commit comment.
