### ISSUE TITLE
Upgrade to Intel SGX 2.8

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#160]
Intel SGX Linux 2.8 has been [released](https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.8-release).

This release contains an interesting new feature for me:
> Added support for running SGX applications inside Docker containers.

Even we have been able to do that with older releases, but now we have official way for that. I think providing a container image is nice, because a user can try our project more easily.

I will try the latest release.

**Comment by ynamiki** [comment]
I cannot find any mentions of the feature in the [documents](https://download.01.org/intel-sgx/sgx-linux/2.8/docs/)....

I think that the release note is wrong and the feature has not been merged in this release; there is an [ongoing issue](https://github.com/intel/linux-sgx/pull/486) in their repository. We may need to wait a next release.

**Comment by nhoriguchi** [comment]
Thanks for the investigation, so let's keep this issue open and wait for the new feature to be released. Could you update the subject of this issue?

**Comment by ynamiki** [comment]
Move to #163.
