### ISSUE TITLE
Improve context info in logger output

### ISSUE THREAD

**Issue by nhoriguchi** [hyperledger-labs/minbft#167]
Currently log messages are printed out with pretty prefix like below:
~~~
[minbft] 06:49:12.203 func1 ▶ DEBU 001 Replica 0: Received <REQUEST client=0 seq=1583477352201795412 operation="c0r0">
[minbft] 06:49:12.204 func1 ▶ DEBU 002 Replica 0: Generated <PREPARE cv=1 replica=0 view=0 client=0 seq=1583477352201795412>
[minbft] 06:49:12.204 handleGeneratedPeerMessages ▶ DEBU 003 Replica 0: Handled <PREPARE cv=1 replica=0 view=0 client=0 seq=1583477352201795412>
[minbft] 06:49:12.726 func1 ▶ DEBU 004 Replica 0: Received <COMMIT cv=1 replica=1 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1583477352201795412>>
~~~
This is a good practice, but I feel that it would be more desirable if we could somehow show context info rather than ambiguous one like 'func1'.

**Comment by nhoriguchi** [comment]
https://github.com/hyperledger-labs/minbft/blob/072cb7503ed5b062fbc9c78afa82cf14a8c319d2/core/replica.go#L27-L31

By setting `defaultLogPrefix` to "longfunc" instead of "shortfunc", log output looks a little more informative like this:
~~~
[minbft] 22:55:42.164 makeMessageStreamHandler.func1 ▶ DEBU 001 Replica 0: Received <REQUEST client=0 seq=1583708142162111507 operation="c0r0">
[minbft] 22:55:42.165 makeGeneratedMessageConsumer.func1 ▶ DEBU 002 Replica 0: Generated <PREPARE cv=1 replica=0 view=0 client=0 seq=1583708142162111507>
[minbft] 22:55:42.165 handleGeneratedPeerMessages ▶ DEBU 003 Replica 0: Handled <PREPARE cv=1 replica=0 view=0 client=0 seq=1583708142162111507>
[minbft] 22:55:42.678 makeMessageStreamHandler.func1 ▶ DEBU 004 Replica 0: Received <COMMIT cv=1 replica=2 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1583708142162111507>>
~~~

**Comment by ynamiki** [comment]
+1. We use anonymous functions a lot so I think this improves the visibility the log.

Note: [Supported verbs](https://pkg.go.dev/github.com/op/go-logging?tab=doc#NewStringFormatter) by go-logging (both `shortfunc` and `longfunc` are "experimental").
Note 2: [This line](https://github.com/hyperledger-labs/minbft/blob/072cb7503ed5b062fbc9c78afa82cf14a8c319d2/core/message-handling.go#L244) outputs the first line of the log in the previous comment.
