### ISSUE TITLE
Move to hyperledger-labs/minbft

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#17]
MinBFT has been [approved](https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/32) as a Hyperledger Lab and a new repository has been created under hyperleder-labs:

https://github.com/hyperledger-labs/minbft

Move contents of this repository to the new one.

**Comment by ynamiki** [comment]
I have confirmed that every commits excluding merge commits in this repository is signed-off at 91aba024a1dd4bbcf7a27991a3bbbf8f6b20bbea so there are no DCO related issues to move.

**Comment by sergefdrv** [comment]
NB: We would need to substitute all occurrences of `github.com/nec-blockchain/minbft` with `github.com/hyperledger-labs/minbft`.

**Comment by ynamiki** [comment]
@sergey, I am going to start the migration to hyperledger-labs after #18 is merged. The following is a migration plan. I would like your comments.

1. Push the latest code (with the commit history) to `hyperledger-labs`.
2. (nec-blockchain) Push a new commit that delete all files and update the README with notice of the migration.
3. (hyperledger-labs) Replace `nec-blockchain/minbft` to `hyperledger-labs/minbft` in the code.
4. (hyperledger-labs) Create issues that are copied from existing open issues in nec-blockchain organization.
5. (nec-blockchain) Close all issues with a link to a corresponding issue in hyperledger-labs organization.
6. (hyperledger-labs) Setup the DCO check and the CI.

**Comment by sergefdrv** [comment]
@ynamiki There seems to be another way to do that: https://help.github.com/articles/about-repository-transfers/. Do you think can we take advantage of it?

**Comment by nhoriguchi** [comment]
@ynamiki README.md on current hyperledger-labs/minbft includes information about committers and sponser, so could you copy it to nec-blockchain/minbft in the migration process?

**Comment by sergefdrv** [comment]
@Naoya-Horiguchi @ynamiki 

> README.md on current hyperledger-labs/minbft includes information about committers and sponser, so could you copy it to nec-blockchain/minbft in the migration process?

Do we have to? As far as I understood "initial committers" means those who would initially have write access to the Hyperledger Labs repository; and sponsor is mainly required to propose for Hyperledger Labs. Anyways, this information is available at https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/labs/minbft.md.

**Comment by ynamiki** [comment]
> There seems to be another way to do that: https://help.github.com/articles/about-repository-transfers/

It seems good. I'll contact the Labs Stewards to use this.

**Comment by ynamiki** [comment]
@sergefdrv I have confirmed (in the chat) that we can transfer by the method. What day would be convenient for you?

**Comment by nhoriguchi** [comment]
>> README.md on current hyperledger-labs/minbft includes information about committers and sponser, so could you copy it to nec-blockchain/minbft in the migration process?
>
> Do we have to? As far as I understood "initial committers" means those who would initially have write access to the Hyperledger Labs repository; and sponsor is mainly required to propose for Hyperledger Labs. Anyways, this information is available at https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/labs/minbft.md.

Ah, OK. So we don't need this step.

**Comment by sergefdrv** [comment]
> What day would be convenient for you?

It doesn't seem to affect anything. So please go ahead any time.

**Comment by ynamiki** [comment]
@sergefdrv @Naoya-Horiguchi We start the transfer. Please suspend updates on this repository including Issues and Pull Requests.

**Comment by ynamiki** [comment]
@ryjones We are ready for the transfer to hyperledger-labs/minbft. Could you start the process?

**Comment by ryjones** [comment]
https://github.com/hyperledger-labs/minbft

**Comment by ryjones** [comment]
@Naoya-Horiguchi has a pending invite to join the committers group, but the transfer is done

**Comment by sergefdrv** [comment]
We still need to adjust import path to finish migration: https://github.com/hyperledger-labs/minbft/issues/17#issuecomment-409853861.
