### ISSUE TITLE
Blocking message stream on handling forwarded Request

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#174]
I am checking the message handling code and have noticed the following. Currently, we don't distinguish whether an incoming connections originates from a client or from another replica: both message streams are eventually handled by the function constructed in `makeMessageStreamHandler`. This function will try to deliver any message produced by the supplied `incomingMessageHandler` as a reply to the handled incoming message. In case of `Request` message, it will return a non-nil `replyChan` and send there a `Reply` message once it is generated.

This works fine when a replica receives a `Request` message form a client, since the client will wait for the `Reply` message on the reply channel. Now we have added request forwarding, a replica might receive `Request` messages forwarded by other replicas, as well. In that case, it will also try supplying the `Reply` message back. However, replicas do not expect any message in reply, so it will block on trying to send the `Reply` message.

@Naoya-Horiguchi When you tested request forwarding, have you experienced any anomaly that would confirm the described problem? I am currently working on changing the message exchange scheme for some other reason. Once I finish, I hope, this issue will be solved, as well. As a quick kludge, we could modify `startPeerConnection` to receive and discard messages from the channel returned by `peerConnector`.

**Comment by nhoriguchi** [comment]
> This works fine when a replica receives a `Request` message form a client, since the client will wait for the `Reply` message on the reply channel. Now we have added request forwarding, a replica might receive `Request` messages forwarded by other replicas, as well. In that case, it will also try supplying the `Reply` message back. However, replicas do not expect any message in reply, so it will block on trying to send the `Reply` message.
>
> @Naoya-Horiguchi When you tested request forwarding, have you experienced any anomaly that would confirm the described problem?

I haven't before but I tested again today, and as you described, the primary peer that received a forwarded `Request` no longer sends REPLY message even in responding to a `Request` from client. What I observed was that the primary replica never prints out log "Generated <REPLY ...>" after processing forwarded `Request`.

> I am currently working on changing the message exchange scheme for some other reason. Once I finish, I hope, this issue will be solved, as well. As a quick kludge, we could modify `startPeerConnection` to receive and discard messages from the channel returned by `peerConnector`.

Thanks for the comment, I tried the quick fix (with below diff) but it seems this doesn't work.
```diff
@@ -285,9 +285,17 @@ func startPeerConnection(connect peerConnector, supply messageSupplier) error {
        // communication, thus return value is ignored. Each replica
        // will establish connections to other peers the same way, so
        // they all will be eventually fully connected.
-       if _, err := connect(out); err != nil {
+       in, err := connect(out)
+       if err != nil {
                return err
        }
+       go func() {
+               for {
+                       select {
+                       case _ = <-in:
+                       }
+               }
+       }()

        go supply(out)
```

It's expected that this code allows peers _forwarding_ the request to receive the reply from the primary peer which processed the forwarded request. But it seems that the primary peer didn't generate `Reply` or send it to anyone, so this code might work to solve the problem. I guess that the problem is in the logic of how the primary peer handles forwarded message.

I'll to dig this more.

**Comment by sergefdrv** [comment]
> the primary peer that received a forwarded `Request` no longer sends REPLY message even in responding to a `Request` from client. What I observed was that the primary replica never prints out log "Generated <REPLY ...>" after processing forwarded `Request`.

Does it print enough corresponding "Received <COMMIT ...>" and "Handled <COMMIT ...>" messages?

**Comment by nhoriguchi** [comment]
> > the primary peer that received a forwarded `Request` no longer sends REPLY message even in responding to a `Request` from client. What I observed was that the primary replica never prints out log "Generated <REPLY ...>" after processing forwarded `Request`.
> 
> Does it print enough corresponding "Received <COMMIT ...>" and "Handled <COMMIT ...>" messages?

Neither of the massages is printed.

Lists of logs of primary peer and backup peer are shown below. In this configuration (N=3, and peer 0 is the primary,) the cluster processed 3 requests:
- the first request messages are sent to all peers,
- the second request messages are sent to peer 1 and 2 (so request forwarding happens,)
- the third request messages are sent to all peers.

So the logs with "cv=3" should be what we are interested in now.

primary peer
```
[minbft] 12:28:37.330 makeMessageStreamHandler.func1 ▶ DEBU 001 Replica 0: Received <REQUEST client=0 seq=1588076917328232472 operation="c0r0">
[minbft] 12:28:37.330 makeGeneratedMessageConsumer.func1 ▶ DEBU 002 Replica 0: Generated <PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>
[minbft] 12:28:37.330 handleGeneratedPeerMessages ▶ DEBU 003 Replica 0: Handled <PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>
[minbft] 12:28:37.851 makeMessageStreamHandler.func1 ▶ DEBU 004 Replica 0: Received <COMMIT cv=1 replica=2 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>>
[minbft] 12:28:37.852 makeMessageStreamHandler.func1 ▶ DEBU 005 Replica 0: Handled <COMMIT cv=1 replica=2 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>>
2020/04/28 12:28:37 Received block[1]: c0r0
[minbft] 12:28:37.852 makeGeneratedMessageConsumer.func1 ▶ DEBU 006 Replica 0: Generated <REPLY replica=0 seq=1588076917328232472 result="{\"Height\":1,\"PrevBlockHash\":null,\"Payload\":\"YzByMA==\"}">
[minbft] 12:28:37.852 makeMessageStreamHandler.func1 ▶ DEBU 007 Replica 0: Received <COMMIT cv=1 replica=1 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>>
[minbft] 12:28:37.853 makeMessageStreamHandler.func1 ▶ DEBU 008 Replica 0: Handled <COMMIT cv=1 replica=1 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>>
2020/04/28 12:28:37 Error receiving from server stream: rpc error: code = Canceled desc = context canceled
[minbft] 12:28:38.873 makeMessageStreamHandler.func1 ▶ DEBU 009 Replica 0: Received <REQUEST client=0 seq=1588076917871033762 operation="c0r1">
[minbft] 12:28:38.873 makeGeneratedMessageConsumer.func1 ▶ DEBU 00a Replica 0: Generated <PREPARE cv=2 replica=0 view=0 client=0 seq=1588076917871033762>
[minbft] 12:28:38.873 handleGeneratedPeerMessages ▶ DEBU 00b Replica 0: Handled <PREPARE cv=2 replica=0 view=0 client=0 seq=1588076917871033762>
[minbft] 12:28:38.877 makeMessageStreamHandler.func1 ▶ DEBU 00c Replica 0: Received <REQUEST client=0 seq=1588076917871033762 operation="c0r1">
2020/04/28 12:28:38 Error receiving from server stream: rpc error: code = Canceled desc = context canceled
[minbft] 12:28:38.896 makeMessageStreamHandler.func1 ▶ DEBU 00d Replica 0: Received <REQUEST client=0 seq=1588076918894168966 operation="c0r2">
[minbft] 12:28:38.896 makeGeneratedMessageConsumer.func1 ▶ DEBU 00e Replica 0: Generated <PREPARE cv=3 replica=0 view=0 client=0 seq=1588076918894168966>
[minbft] 12:28:38.896 handleGeneratedPeerMessages ▶ DEBU 00f Replica 0: Handled <PREPARE cv=3 replica=0 view=0 client=0 seq=1588076918894168966>
2020/04/28 12:28:38 Error receiving from server stream: rpc error: code = Canceled desc = context canceled

```
backup peer
```
[minbft] 12:28:37.331 makeMessageStreamHandler.func1 ▶ DEBU 001 Replica 1: Received <REQUEST client=0 seq=1588076917328232472 operation="c0r0">
[minbft] 12:28:37.847 makeMessageStreamHandler.func1 ▶ DEBU 002 Replica 1: Received <PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>
[minbft] 12:28:37.848 makeGeneratedMessageConsumer.func1 ▶ DEBU 003 Replica 1: Generated <COMMIT cv=1 replica=1 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>>
[minbft] 12:28:37.848 makeMessageStreamHandler.func1 ▶ DEBU 004 Replica 1: Handled <PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>
[minbft] 12:28:37.848 handleGeneratedPeerMessages ▶ DEBU 005 Replica 1: Handled <COMMIT cv=1 replica=1 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>>
2020/04/28 12:28:37 Received block[1]: c0r0
[minbft] 12:28:37.848 makeGeneratedMessageConsumer.func1 ▶ DEBU 006 Replica 1: Generated <REPLY replica=1 seq=1588076917328232472 result="{\"Height\":1,\"PrevBlockHash\":null,\"Payload\":\"YzByMA==\"}">
[minbft] 12:28:37.850 makeMessageStreamHandler.func1 ▶ DEBU 007 Replica 1: Received <COMMIT cv=1 replica=2 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>>
[minbft] 12:28:37.850 makeMessageStreamHandler.func1 ▶ DEBU 008 Replica 1: Handled <COMMIT cv=1 replica=2 prepare=<PREPARE cv=1 replica=0 view=0 client=0 seq=1588076917328232472>>
2020/04/28 12:28:37 Error receiving from server stream: rpc error: code = Canceled desc = context canceled
[minbft] 12:28:37.873 makeMessageStreamHandler.func1 ▶ DEBU 009 Replica 1: Received <REQUEST client=0 seq=1588076917871033762 operation="c0r1">
[minbft] 12:28:38.873 makePrepareTimerStarter.func1.1 ▶ INFO 00a Replica 1: Prepare timer expired: client=0 seq=1588076917871033762 view=0
[minbft] 12:28:38.874 makeMessageStreamHandler.func1 ▶ DEBU 00b Replica 1: Received <COMMIT cv=2 replica=2 prepare=<PREPARE cv=2 replica=0 view=0 client=0 seq=1588076917871033762>>
[minbft] 12:28:38.875 makeGeneratedMessageConsumer.func1 ▶ DEBU 00c Replica 1: Generated <COMMIT cv=2 replica=1 prepare=<PREPARE cv=2 replica=0 view=0 client=0 seq=1588076917871033762>>
[minbft] 12:28:38.875 makeMessageStreamHandler.func1 ▶ DEBU 00d Replica 1: Handled <COMMIT cv=2 replica=2 prepare=<PREPARE cv=2 replica=0 view=0 client=0 seq=1588076917871033762>>
[minbft] 12:28:38.875 handleGeneratedPeerMessages ▶ DEBU 00e Replica 1: Handled <COMMIT cv=2 replica=1 prepare=<PREPARE cv=2 replica=0 view=0 client=0 seq=1588076917871033762>>
2020/04/28 12:28:38 Received block[2]: c0r1
[minbft] 12:28:38.875 makeGeneratedMessageConsumer.func1 ▶ DEBU 00f Replica 1: Generated <REPLY replica=1 seq=1588076917871033762 result="{\"Height\":2,\"PrevBlockHash\":\"1IHbQT2av2WvmpLmmA0C9MgbWtn72NOVS9hK+atUUTo=\",\"Payload\":\"YzByMQ==\"}">
[minbft] 12:28:38.875 makeMessageStreamHandler.func1 ▶ DEBU 010 Replica 1: Received <PREPARE cv=2 replica=0 view=0 client=0 seq=1588076917871033762>
[minbft] 12:28:38.876 makeMessageStreamHandler.func1 ▶ INFO 011 Replica 1: Dropped <PREPARE cv=2 replica=0 view=0 client=0 seq=1588076917871033762>
2020/04/28 12:28:38 Error receiving from server stream: rpc error: code = Canceled desc = context canceled
[minbft] 12:28:38.895 makeMessageStreamHandler.func1 ▶ DEBU 012 Replica 1: Received <REQUEST client=0 seq=1588076918894168966 operation="c0r2">
[minbft] 12:28:38.898 makeMessageStreamHandler.func1 ▶ DEBU 013 Replica 1: Received <COMMIT cv=3 replica=2 prepare=<PREPARE cv=3 replica=0 view=0 client=0 seq=1588076918894168966>>
[minbft] 12:28:38.898 makeGeneratedMessageConsumer.func1 ▶ DEBU 014 Replica 1: Generated <COMMIT cv=3 replica=1 prepare=<PREPARE cv=3 replica=0 view=0 client=0 seq=1588076918894168966>>
[minbft] 12:28:38.898 makeMessageStreamHandler.func1 ▶ DEBU 015 Replica 1: Handled <COMMIT cv=3 replica=2 prepare=<PREPARE cv=3 replica=0 view=0 client=0 seq=1588076918894168966>>
[minbft] 12:28:38.898 makeMessageStreamHandler.func1 ▶ DEBU 016 Replica 1: Received <PREPARE cv=3 replica=0 view=0 client=0 seq=1588076918894168966>
[minbft] 12:28:38.899 makeMessageStreamHandler.func1 ▶ INFO 017 Replica 1: Dropped <PREPARE cv=3 replica=0 view=0 client=0 seq=1588076918894168966>
[minbft] 12:28:38.899 handleGeneratedPeerMessages ▶ DEBU 018 Replica 1: Handled <COMMIT cv=3 replica=1 prepare=<PREPARE cv=3 replica=0 view=0 client=0 seq=1588076918894168966>>
2020/04/28 12:28:38 Received block[3]: c0r2
[minbft] 12:28:38.899 makeGeneratedMessageConsumer.func1 ▶ DEBU 019 Replica 1: Generated <REPLY replica=1 seq=1588076918894168966 result="{\"Height\":3,\"PrevBlockHash\":\"KK6OcXuCIlYXFAVMvtm+/kAPMfXPZH778YgKhIAIeUg=\",\"Payload\":\"YzByMg==\"}">
2020/04/28 12:28:38 Error receiving from server stream: rpc error: code = Canceled desc = context canceled
2020/04/28 12:28:39 Error receiving from replica 0: rpc error: code = Unavailable desc = transport is closing
2020/04/28 12:28:39 Error receiving from server stream: rpc error: code = Canceled desc = context canceled
```

**Comment by sergefdrv** [comment]
So the primary does not produce Reply messages because it stops receiving Commit message after it has received the forwarded Request...

**Comment by nhoriguchi** [comment]
I wondered how the primary peer printed the error log "Error receiving from server stream: rpc error: code = Canceled desc = context canceled", and found that It was printed by goroutine in `(*replyState)#ReplyChannel()` called from `requestReplier`. The root cause of this is that the primary peer receives 2 forwarded REQUESTs with the same sequence number, and the second one is not handled properly. We have duplicate checking mechanism `captureSeq()` and if it detects REQUEST with already captured seq, `requestProcessor` returns `new=false` and `err=nil`. These return values are propagated to `messageStreamHandler`. But curiously, `messageStreamHandler` does not drop the second REQUEST even if `new` is false, because `handle()` returns non-nil `replyChan`.

Reordering return checks like below solves this specific issue of channel blocking:
```
                        if replyChan, new, err := handle(msg, false); err != nil {
                                logger.Warningf("Failed to handle %s: %s", msgStr, err)
+                       } else if !new {
+                               logger.Infof("Dropped %s", msgStr)
                        } else if replyChan != nil {
                                m, more := <-replyChan
                                if !more {
                                        continue
                                }
                                replyBytes, err := m.MarshalBinary()
                                if err != nil {
                                        panic(err)
                                }
                                reply <- replyBytes
-                       } else if !new {
-                               logger.Infof("Dropped %s", msgStr)
                        } else {
                                logger.Debugf("Handled %s", msgStr)
                        }
```
, but that might have some unexpected impact on the other handling path for `messages.PeerMessage`. We have similar duplicate checking `captureUI` for `messages.PeerMessage`, so I feel that checking `!new` first makes sense. Can I have your ideas on this point?

**Comment by sergefdrv** [comment]
> ... `messageStreamHandler` does not drop the second REQUEST even if `new` is false, because `handle()` returns non-nil `replyChan`

This is because we need to send a REPLY message to the client even if the corresponding REQUEST message has been processed before. Imagine the replica receives and processes the REQUEST message embedded into a PREPARE message before receiving it directly from the client. Nevertheless, the client might still need to receive the REPLY message to collect a sufficient quorum. This is one reason why REPLY messages are always sent to the client in response.

> We have similar duplicate checking `captureUI` for `messages.PeerMessage`

`captureUI` in `makeUIMessageProcessor` will only return `new == false` if the message was already processed. Subsequent message processing stages rely that such messages are processed only once.

**Comment by sergefdrv** [comment]
@Naoya-Horiguchi Could you please check if #175 helps to resolve this issue?

**Comment by nhoriguchi** [comment]
> @Naoya-Horiguchi Could you please check if #175 helps to resolve this issue?

Sorry for the late response, I confirmed that #175 fixes this issue.

> > ... `messageStreamHandler` does not drop the second REQUEST even if `new` is false, because `handle()` returns non-nil `replyChan`
> 
> This is because we need to send a REPLY message to the client even if the corresponding REQUEST message has been processed before. Imagine the replica receives and processes the REQUEST message embedded into a PREPARE message before receiving it directly from the client. Nevertheless, the client might still need to receive the REPLY message to collect a sufficient quorum. This is one reason why REPLY messages are always sent to the client in response.

I agree that a client should always receive REPLY for a REQUEST whichever paths the replicas accept it from (directly from the client, REQUEST embedded in PREPARE, or forwarded REQUEST). But "exactly one" REPLY or "at least one" REPLY(s) should be clear because client applications have to decide how to handle duplicated REPLYs. As long as I reviewed #175, "exactly one" REPLY is intended (because 2nd forwarded REQUEST is dropped with that change) and I think that's a good choice.

BTW, our sample client might want to check duplication of REPLY messages.

**Comment by sergefdrv** [comment]
> > @Naoya-Horiguchi Could you please check if #175 helps to resolve this issue?
> 
> Sorry for the late response, I confirmed that #175 fixes this issue.

Great news! I know you had holidays in Japan. Thanks for making the checks :slightly_smiling_face: 

> BTW, our sample client might want to check duplication of REPLY messages.

I believe it already does the check [here](https://github.com/hyperledger-labs/minbft/blob/9f0b3f20bb377c35989dd51028370490edfb9b03/client/internal/requestbuffer/requestbuffer.go#L223). Admittedly, the design of the `client` package differs from the `core` package because it was implemented earlier. We might like to adjust it later to match the newer approach implemented in `core`...
