### ISSUE TITLE
Update the CI environment

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#182]
Before the upcoming release, update the dependencies, the CI environment, and README to use the latest releases:

- [x] Dependencies
- [x] Ubuntu (CI)
- [x] Intel SGX SDK (CI)
- [x] Go (CI)
- [x] GolangCI-Lint (CI)
- [x] README

**Comment by sergefdrv** [comment]
We might also like to check other direct dependencies in `go.mod` for useful updates.

**Comment by ynamiki** [comment]
Done by #185 and #190.
