### ISSUE TITLE
Enabling "Dismiss stale pull request approvals when new commits are pushed" in the project settings

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#191]
I feel that I have to withdraw my approval, but there seems no way for it. Enabling "Dismiss stale pull request approvals when new commits are pushed" setting in branch protection tab (see below) would help us, although I don't have permission to change it on this project. If you think it's helpful, let's enable the setting.

![image](https://user-images.githubusercontent.com/378762/83203106-ab99ea00-a183-11ea-876e-7fa0f690f13a.png)

_Originally posted by @Naoya-Horiguchi in https://github.com/hyperledger-labs/minbft/pull/190#issuecomment-635665845_

**Comment by ynamiki** [comment]
We need to contact the LF Admin team to update the configuration. I'll do it.

**Comment by ynamiki** [comment]
I have contacted [the LF Help Desk](http://support.linuxfoundation.org/) [IT-19857]. Waiting a response.

**Comment by ynamiki** [comment]
@sergefdrv @Naoya-Horiguchi The setting has been updated by the LF team. If it seems not working, please re-open this issue.

**Comment by nhoriguchi** [comment]
Thank you for your effort. We'll check how the setting works in next reviews.
