### ISSUE TITLE
Repository changes

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#199]
I noticed some changes happened to this repository.  

 - [`minbft-committers` team](https://github.com/orgs/hyperledger-labs/teams/minbft-committers) was removed from GitHub
 - CODEOWNDERS doesn't seem work properly (e.g. #198 was not assigned to any reviewer initially)

@ynamiki Do you know who has maintainer role in the repository? Do you have contact with HL to clarify this?

**Comment by ynamiki** [comment]
Thanks, I have not noticed the effect. I will contact the HL team to clarify this.

**Comment by ynamiki** [comment]
I have got a response but there is no answer about the maintainers.... It is confirmed that current contributors do not have write permissions, so I ask for the permission in my reply.

**Comment by sergefdrv** [comment]
Thank you for taking care of this. We at least need to be able to change issue/PR attributes, like assignees, labels etc. It's also unclear how to make automatic reviewer assignment work again.

**Comment by sergefdrv** [comment]
I checked [the docs](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners), and I think our code owners indeed need "write" level permission for the repository:

> The people you choose as code owners must have write permissions for the repository.

**Comment by ynamiki** [comment]
@sergefdrv @Naoya-Horiguchi Now we have write permissions again!

It seems that we are [outside collaborators](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization) of the organization hyperledger-labs, and have [write permission](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) in this repository.

Note: I sent request from [Linux Foundation's Help Center/Project Services](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2).
