### ISSUE TITLE
Update System Requirements (Go 1.12 or later)

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#203]
CI with Go 1.11 has failed because some updated dependency requires at least Go 1.12. Maybe it's time to drop support for Go 1.11 since [current stable versions](https://golang.org/dl/) of Go are 1.15 and 1.16.

_Originally posted by @sergefdrv in https://github.com/hyperledger-labs/minbft/issues/202#issuecomment-838352731_

**Comment by ynamiki** [comment]
I plan to choose Go 1.13 in the minimal system requirements. The followings are why I choose this version: (1) Go 1.12 is our earliest required version, (2) Go 1.14 or earlier are no longer supported by the Go community, and (3) Go 1.13 is provided by [Ubuntu 20.04](https://packages.ubuntu.com/focal/golang-go) packages, which means the version supported by the Ubuntu community.

For the CI, I will update to use Go 1.13 and 1.16, the latest version.

**Comment by ynamiki** [comment]
Sorry, #202 covers this issue.

**Comment by sergefdrv** [comment]
> Go 1.13 is provided by [Ubuntu 20.04](https://packages.ubuntu.com/focal/golang-go) packages, which means the version supported by the Ubuntu community.

Good point, we might support 1.13, as well
