### ISSUE TITLE
Set default branch to `main`

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#209]
As noted in [this email](https://lists.hyperledger.org/g/labs/message/145), Hyperledger Labs should, similar to Hyperledger Projects, move from `master` to `main` for the default branch. MinBFT also needs to do the switch.

**Comment by ynamiki** [comment]
@sergefdrv @nhoriguchi I'll contact Ry for updating the setting if you are OK to do it now.

**Comment by sergefdrv** [comment]
We don't have any open pull requests, so it should be fine.

**Comment by ynamiki** [comment]
I've sent a request. The setting will be updated soon.

**Comment by ynamiki** [comment]
Done.
