### ISSUE TITLE
Fix CI after migration to Hyperledger Labs

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#21]
Seems like CircleCI stopped working since migration to Hyperledger Labs. Pull requests, at least, do not go through CI.

**Comment by ynamiki** [comment]
I have finished the configuration:
https://circleci.com/gh/hyperledger-labs/minbft

The build status badge in the README is updated in #22.
I will close this issue after #22 is merged.

**Comment by sergefdrv** [comment]
NB. https://help.github.com/articles/closing-issues-using-keywords/
