### ISSUE TITLE
Enable LGTM automated security analysis

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#221]
[LGTM](https://lgtm.com/help/lgtm/about-lgtm) is a security analysis platform that can automatically check code for real CVEs and vulnerabilities. We might want to enable it for MinBFT.

**Comment by nhoriguchi** [comment]
I'm fine with using it, which might allow us to avoid introducing common security issues.

**Comment by ynamiki** [comment]
We need to install the LGTM GitHub App to enable the functions. I will contact the LF IT team to request the installation.
https://lgtm.com/help/lgtm/github-apps-integration

**Comment by ynamiki** [comment]
Ry is trying to enable the LGTM GitHub App for this repository. He will create some PRs to test the integration; we can ignore the PRs.

**Comment by ynamiki** [comment]
The LGTM GitHub App has been enabled. No alearts for the HEAD. A check by the app will be triggered in a next pull request.
https://lgtm.com/projects/g/hyperledger-labs/minbft/
