### ISSUE TITLE
LGTM analysis skipped on force-push

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#231]
It looks like LGTM analysis is [skipped](https://github.com/hyperledger-labs/minbft/pull/229#event-5901752037) after a [force-push](https://github.com/hyperledger-labs/minbft/pull/229#event-5893533842). Could you please help to fix this?

**Comment by sergefdrv** [comment]
I can confirm LGTM analysis was also skipped after a force-push in #230.

**Comment by ynamiki** [comment]
I will ask for help from the LF IT support team. Sorry for my late response.

**Comment by sergefdrv** [comment]
LGTM analysis seems to work on force-pushes now, thanks!
