### ISSUE TITLE
Benchmarking the code in distributed settings

### ISSUE THREAD

**Issue by dgiantsidi** [hyperledger-labs/minbft#252]
Hi there,

I 'd like to benchmark minbft in a distributed setting of 5-6 machines. 
Is there any documentation for that? 
I dig into the code and made some changes that mostly aim to solve the connectivity issues. So instead of relying on the docker-compose network I used the host network with the host-ip addresses (in a local machine though--not yet distributed).
It looks like that replicas and the client can connect to each other successfully but the authentication process fails with the error ("invalid signature" or smth like that). 

I additionally tried to run multiple clients by creating multiple docker-images (client1-client2-client3). It looks like that the clients timeout when they run concurrently (I increased the timeout periods to 10s or so, but still the client crashes).

Any help would be highly appreciated -- thanks in advance

Best,
Dimitra

**Comment by nhoriguchi** [comment]
@dgiantsidi Thank you for experimenting with minbft.

> Is there any documentation for that?

Unfortunately not.

> I dig into the code and made some changes that mostly aim to solve the connectivity issues. So instead of relying on the docker-compose network I used the host network with the host-ip addresses (in a local machine though--not yet distributed).
> It looks like that replicas and the client can connect to each other successfully but the authentication process fails with the error ("invalid signature" or smth like that).

I feel that you might see the error because you build with `make install` separately in each hosts. If that's true (sorry if not...), you might work around this by building in one host and then copying the deliverables (especially `lib/libusig.signed.so` and `lib/libusig_shim.so`) to the other hosts.

**Comment by dgiantsidi** [comment]
Hi there,

@nhoriguchi  thank you for your reply. 

Our cluster runs an NFS so all files, binaries, libraries are visible to all servers. 
What I tried (unfortunately with no luck) is to build the docker-image in one host and then "copy" this image to all other servers without re-building it (as nfs by default does not copy these). The same error persists; replica 0 receives the request but fails to authenticate the tag (due to invalid signature error). 

Is it possible that this has to do with the ``sample/docker/keys.yaml`` file. I am not touching it, it is visible to all servers .. just wondering if there is a key exchange at the initialization, etc.

Best,
Dimitra

**Comment by nhoriguchi** [comment]
Hi,

> Our cluster runs an NFS so all files, binaries, libraries are visible to all servers.
> What I tried (unfortunately with no luck) is to build the docker-image in one host and then "copy" this image to all other servers without re-building it (as nfs by default does not copy these). The same error persists; replica 0 receives the request but fails to authenticate the tag (due to invalid signature error).

Did you test in SGX HW mode, or in simulation mode? I checked that consensus properly worked on 3-node cluster (each node running on separate EC2 instance without docker), where each node has the setting `SGX_MODE=SIM` (I don't check with `SGX_MODE=HW` myself because no SGX-enabled instance is available to me now).

> Is it possible that this has to do with the sample/docker/keys.yaml file. I am not touching it, it is visible to all servers .. just wondering if there is a key exchange at the initialization, etc.

So I don't think so, each node can have the identical keys.yaml (at least in testing system).

**Comment by dgiantsidi** [comment]
Hello,

I tested with ```SGX_HW=SIM``` each of the process runs in a docker container. 
The reason for using docker is that we deploy NixOS in our cluster and as such building the SGX drivers etc. requires some engineering from my side. 
For the network interfaces, IPs, etc. to be available I use the ```--network host``` option when deploying docker.

--dimitra

**Comment by nhoriguchi** [comment]
We only test a few specific sets of OS and SGX driver versions, so I have no idea of the root cause of your error, sorry.

**Comment by dgiantsidi** [comment]
Okay @nhoriguchi,

Thank you for your help and time :) 
I am closing this for the moment.

--dimitra
