### ISSUE TITLE
Switch to new go version

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#3]
`go1.10` is out there. Use it!

**Comment by ynamiki** [comment]
@sergefdrv Let me clarify a goal of this Issue.
Since Go 1.10 has no significant changes to the language specification, is updating [Dockerfiles](https://github.com/nec-blockchain/minbft/tree/master/dockerfiles) enough for this?

**Comment by sergefdrv** [comment]
@ynamiki Exactly, that is only about updating Dockerfiles and Readme. That means this issue is to be concerned after #7 is resolved.
