### ISSUE TITLE
Remove nolint from core/usig/sgx/usig-enclave.go.in

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#4]
`gometalinter` should work fine after https://github.com/alecthomas/gometalinter/issues/450 was fixed.

**Comment by nhoriguchi** [comment]
@sergefdrv the mentioned issue was fixed for go-1.9 and 1.10. So can we close this issue?

**Comment by sergefdrv** [comment]
@Naoya-Horiguchi Yes, it was fixed. The only thing left is to remove the `// nolint` hint from our source code https://github.com/nec-blockchain/minbft/blob/master/usig/sgx/usig-enclave.go.in#L68
