### ISSUE TITLE
Consider faulty client

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#5]
Faulty client might:
- not send a Request message to the primary
- send conflicting Request messages to different replicas

This could lead to expiration of the request timer and view change even if the primary is not faulty. This way liveness may be compromised.

**Comment by sergefdrv** [comment]
Intuitively, #29 should fix the case 2, where the malicious client sends conflicting request IDs to different replicas. One option to fix the case 1 could be for a backup replica to forward client requests to the primary if there's no corresponding Prepare message within certain timeout, less than the request timeout.

**Comment by nhoriguchi** [comment]
I think that we could introduce kind of "prepare timer" to detect case 1. But I'm not sure how replicas should respond to such events. Triggering view changes might not be the best option because that mean malicious clients easily/intentionally trigger view changes. If a client doesn't send (the same) request messages to *all* replicas, that request could be considered as "not finish submission process" so could be ignored silently. Maybe request timer also should trigger view changes only after confirming that the related request is properly submitted (f.e. complete the prepare phase?)

**Comment by sergefdrv** [comment]
It seems that we cannot distinguish whether the client did not send the request to the primary, or the primary ignored it. I think the request timer should only initiate view change, if the replica is sure the primary had a chance to prepare the request. To that end, backup replicas might have to relay pending unprepared requests to the primary at some point. 

One approach is to relay the request upon the first expiration of the request timer, then restart it, and initiate view change if the request timer fires again. 

Another approach could be to introduce a dedicated timer, as you called it "prepare timer", that will trigger relaying the request to the primary. Once the request is relayed or prepared, the normal request timer should be started to initiate a view change if expired. 

I tend to slightly prefer the second approach. 

@jcs47 What do you think?

**Comment by nhoriguchi** [comment]
> It seems that we cannot distinguish whether the client did not send the request to the primary, or the primary ignored it. I think the request timer should only initiate view change, if the replica is sure the primary had a chance to prepare the request. To that end, backup replicas might have to relay pending unprepared requests to the primary at some point.

OK, this is the precise description of the current problem.

> ...
> I tend to slightly prefer the second approach.

Thanks for the feedback. I'll write some code with the second approach. Maybe we might want to give shorter timeout value for "prepare timer" than the request timer, so that gives another reason for an additional timer.
