### ISSUE TITLE
Include message type to signed payload

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#6]
The message type should be covered by signature/USIG certificate to guarantee that a singed payload will not happen to be misinterpreted. NB: Protobuf does not include the message type into the binary encoding.

**Comment by nhoriguchi** [comment]
My brief search shows that protobuf supports [message type `Any`](https://developers.google.com/protocol-buffers/docs/proto3#any) and golang provides [the related package](https://godoc.org/github.com/golang/protobuf/ptypes/any) which should provide the functionality to embed the message type info into the message itself. Currently our project depends on the older version of protobuf (v1.3.1), so if we want to go in this direction we will start with updating protobuf version (which might cause unexpected issues).

**Comment by sergefdrv** [comment]
I think first step to take would be defining an abstract interface for messages, thus separating message usage from message representation. Another thing to consider is that the signed/certified serialized message payload should be retained in its original form, so that validation will be reliable even if different node would use different version of Protobuf generating slightly different serialized binaries.

Now, I'm actually experimenting with similar kind of task. Maybe I could solve this issue using the gained experience, before introducing view-chage message types.

**Comment by nhoriguchi** [comment]
This issue seems to be solved by #122, so can we close this or do we have remaining items?

BTW, have a nice holidays!

**Comment by sergefdrv** [comment]
In fact, #122 was a preparation step to solve this issue in isolation from the core protocol logic. Messages' signed/certified payloads are still the same, i.e. missing any payload type designator/tag. I have solved similar problem somewhere else and plan to solve this issue in similar way.

**Comment by sergefdrv** [comment]
Have nice holidays, too. Btw, I'll be fully back from Jan 2.
