### ISSUE TITLE
Re-enable CircleCI checks in pull requests

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#65]
CircleCI checks stopped functioning in pull requests recently, e.g. #64. We need to re-enable it.

**Comment by ynamiki** [comment]
@sergefdrv It may sound strange, but I have not changed the configuration and my test PR (#66) triggered CircleCI without any problem.

[CircleCI will skip a build](https://circleci.com/docs/2.0/skip-build/) if `[ci skip]` or `[skip ci]` is included in a commit title or a description. But there are no such keywords in your commits.

I am sorry but I cannot identify a root cause. Could you please re-try a build by force-pushing into the branch if CircleCI is not triggered?

**Comment by sergefdrv** [comment]
@ynamiki Lets keep an eye on it and see how it behaves next time. I remember I also had to do force-push in #62 to trigger CI.

I suspected that CI might not have been triggered because CircleCI was triggered against my private fork before I opened PR, but that should not be the case...

**Comment by sergefdrv** [comment]
#70 did not trigger CI...

**Comment by ynamiki** [comment]
I have no idea of the cause. The CI will not be triggered if a PR is opened by someone other than me...? I will look for related configuration.

**Comment by ynamiki** [comment]
My PR #72 triggered the CI successfully🤔 (I have not changed any configuration).

**Comment by sergefdrv** [comment]
#74 didn't trigger CI...

**Comment by ynamiki** [comment]
I confirmed that GitHub triggers [the webhook](https://github.com/hyperledger-labs/minbft/settings/hooks/91605216) properly (e.g. `6cb75600-4159-11e9-8ca1-063fdf0a7fa5` for opening #75) and CircleCI replied 200 as a response. It seems that this is a matter of CircleCI (not GitHub).

**Comment by sergefdrv** [comment]
Apparently, CircleCI Check's app has no access to code https://github.com/apps/circleci-checks/installations/718224. This might be the problem, as well...

**Comment by sergefdrv** [comment]
Seems to have worked for #76.

**Comment by ynamiki** [comment]
The CI has NOT triggered by #76 itself, but by merging it into `master`.
It seems that there are something wrong for a forked PR.

**Comment by sergefdrv** [comment]
That's strange, I'm pretty sure I've seen CI check passed before I merged the #76. But I didn't go to the "Checks" tab; I looked at the panel on "Conversation" tab, just above "Merge" button. Let's keep it open and observe the behavior with the next PR.

**Comment by sergefdrv** [comment]
Maybe, that was the case because @Naoya-Horiguchi  force-pushed the branch after the PR was created. I observed that behavior before: force push somehow triggers CI.

**Comment by ynamiki** [comment]
In #83, we confirmed the CI has been triggered for a PR that is opened by other than @ynamiki; it looks it works well!

**Comment by sergefdrv** [comment]
Unfortunately, is CI still not triggered by my PRs, e.g. #91 :slightly_frowning_face:

**Comment by ynamiki** [comment]
I have re-configured the CircleCI integration (with help from the LF helpdesk). It looks good for me (#92).
I will close this issue if we confirm that the CI is triggered for a PR by others (i.e. not me).

**Comment by sergefdrv** [comment]
@ynamiki Thanks for handling this! Hope it works now. NB: it seemed to worked before if one force pushed once, _after_ PR was created. So let's wait and see if it works with a newly created PR.

**Comment by sergefdrv** [comment]
#94 doesn't show CircleCI status in "Checks", although CI was triggered by the push in the branch to merge, as indicated by :heavy_check_mark:: https://github.com/sergefdrv/minbft/commits/add-request-timer-v2.

**Comment by sergefdrv** [comment]
I noticed that we have both GitHub App and a Web Hook for CircleCI enabled. Maybe there is some conflict and we should leave only one thing on?

**Comment by ynamiki** [comment]
I have deleted the webhook. I keep an eye on how it works with this configuration....

**Comment by ynamiki** [comment]
After deleting the webhook, merging #94 into master did not trigger the CI. I restored the webhook.

**Comment by sergefdrv** [comment]
Unfortunately, #95 hasn't triggered CI... :slightly_frowning_face:

**Comment by sergefdrv** [comment]
I think there is some issue with my account. #102 didn't trigger CI, but #101 did. I need to investigate it myself, then.

**Comment by ynamiki** [comment]
#104 from @sergefdrv did trigger the CI. The problem is solved...?

**Comment by sergefdrv** [comment]
@ynamiki Now CircleCI is properly triggered by my PR. What I did was to disable CircleCI for my fork of the repo. I am fine with that, but I wonder why that was an issue. Maybe, I try to enable it again and see how will that go...

**Comment by sergefdrv** [comment]
Maybe we can now require CircleCI [status check](https://help.github.com/en/articles/enabling-required-status-checks) for `master` branch?

**Comment by ynamiki** [comment]
@sergefdrv @Naoya-Horiguchi Now CircleCI status check is required for `master` branch. Please let me know if you have any trouble.
