### ISSUE TITLE
Enable CI in GitHub

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#7]
GitLab CI was used for this project internally. In order to see CI results in GitHub, it should be re-enabled using whatever GitHub supports.

**Comment by ynamiki** [comment]
@sergefdrv Do you have a preference on CI service?
I think a free cloud-hosted service ([CircleCI](https://circleci.com/), [Travis CI](https://travis-ci.org/), ...) is a good option as the first step.
GitLab recently releases [GitLab CI/CD for GitHub](https://about.gitlab.com/features/github/); this could also be an option with minimal porting cost.

**Comment by sergefdrv** [comment]
Although using GitLab CI/CD for GitHub sounds attractive because of minimal efforts, apparently that requires a mirror repository on GitLab.com. Are we up to create one? I don't mind investigating other options supported by GitHub.

**Comment by ynamiki** [comment]
I will try Travis CI.
