### ISSUE TITLE
Enable Developer Certificate of Origin (DCO) Checks

### ISSUE THREAD

**Issue by ynamiki** [hyperledger-labs/minbft#8]
Install a GitHub App that enforces the Developer Certificate of Origin (DCO) on commits.

https://github.com/probot/dco

**Comment by sergefdrv** [comment]
This requires special permission for the repo

**Comment by ynamiki** [comment]
I have installed [probot/dco](https://github.com/apps/dco).
According to the [document](https://github.com/probot/dco/blob/master/docs/required-statuses.md), opening a Pull Request is needed before configuration; I will complete the configuration after we receive a Pull Request.

**Comment by ynamiki** [comment]
The configuration has been completed.
