### ISSUE TITLE
Make usig/sgx package retrievable from the repository

### ISSUE THREAD

**Issue by sergefdrv** [hyperledger-labs/minbft#87]
Now the main code base is converted to a Go module. However, we cannot fully utilize flexibility and convenience of Go module system due to the fact that `usig/sgx` is still a special package. That is because `usig/sgx/usig-enclave.go` has to be generated with `make`. This means a module user cannot retrieve this package directly from the repository, but needs to build it separately. We should change the way we build the enclave to make this an ordinary Go package.

To achieve this, we need to break the dependency of cgo code on SGX SDK dynamic libraries. In other words, building of the encalve-related C stuff needs to be split from the main Go code base.

Making the enclave wrapper (shim) library a dynamically-linked module (using `dlopen()` in cgo code) seems to be a good option to achieve this.

For more details, please refer to [the original discussion starting here](https://github.com/hyperledger-labs/minbft/pull/72#issuecomment-481881753).

**Comment by nhoriguchi** [comment]
There's a ongoing discussion about Go-plugin, but I think this specific issue is solved by #115. So let's close this.
